### ISSUE TITLE
Question: Smart limiting/grouping of 2D spatial sound instances

### ISSUE THREAD

**Issue by Frotty** [Hangman/TuningFork#11]
Hi, I'm looking for a sound library and this one seems pretty cool since I am using the jwgl3 backend anyways.
I have a small question whether this library supports an easy way to (smartly) limit/group multiple spatial 2d sound emitters?
In my use case i have a 2d game where there are enemies (spiders) which emit a constant looping movement sound (crawling).
There can be tens of spiders in a level. Of course I don't want to play the same looped sounds tens of times because it sounds awful.
I would like there to only be like 2-4 instances, depending on where the spiders are located.
E.g. if there are multiple spiders left and right of the player, it should only play one 2d sound on the left, and one on the right, etc.
The grouping/limit should also update when the player moves.
Right now I only have a very naive sound instance limitation, which can cause problems with many spiders because only certain spiders emit sounds and it's not consistent, especially when moving around.
Is there any easy way to achieve this with this library?

**Comment by Hangman** [comment]
Hi!
I think the problem consists of 2 different parts.
1. Sound part: panning, volume distance attenuation, optionally distance reverberation
2. Finding groups: determine which and how many spiders should be grouped together and linked to a single sound source and where its center is located.

The library does part 1 pretty much automatically, without having you to take care of anything but the position. You just set the position in 3D space (in your case you just set Y or Z to 0 to make it 2D) and that's it. Panning, volume distance attenuation, and if needed distance reverberation are automatically adjusted by the library.

Part 2 is quite a complex problem and very individual, so I'd rather leave this to the application, I think it's out of scope of this library.
What you are looking for is probably a grouping/clustering algorithm.
[K-means](https://en.wikipedia.org/wiki/K-means_clustering) looks promising to give a good result audiowise. Oh nice, there's a Baeldung article about it [here](https://www.baeldung.com/java-k-means-clustering-algorithm).
If performance is more important, I think your approach is actually sufficient. Splitting into left and right should not cost very much computing power. Also splitting into quarters could be an option to achieve a better result.
