### ISSUE TITLE
Filter only works for really small values.

### ISSUE THREAD

**Issue by Leshy-YA** [Hangman/TuningFork#5]
When using

- filter.setLowFrequencyVolume(float volume)
- filter.setHighFrequencyVolume(float volume)

there isn't any audible change for values of volume 0.2 - 1.0.
Only for very small values the relevant frequencies seem to get turned down.

**Comment by Hangman** [comment]
Hi, I just tested it with different sounds and I can hear the difference about up to 0.6 on my speakers and up to 0.9 on my headphones.
However, it is very dependent on the frequencies present in the sound being played and the quality of the speakers as to how well you can perceive the difference.

For the human ear it is not linear though. The frequency suppression from 0.2 to 0.1 has a stronger effect than from 0.3 to 0.2, for example.

If you want me to check the whole thing with a sound file from you, feel free to send me one.

**Comment by Leshy-YA** [comment]
Ok!
I've ran some more scientific tests. Created a 440 Hz square wave and indeed the filter works as intended. 
There must be something peculiar with the audio track I used.
