### ISSUE TITLE
Error when applying SoundEffect

### ISSUE THREAD

**Issue by 4lfg24** [Hangman/TuningFork#8]
Hi I tried to apply a Reverb effect to my soundsource like this: 
```sound = WaveLoader.load("numbers.wav".toInternalFile())
        soundSource = audio.obtainSource(sound)
        soundSource.setRelative(true)
        soundSource.setLooping(true)

        var effect = SoundEffect(Reverb())
        soundSource.attachEffect(effect)

        soundSource.play()
```

But then I get this error:
```failed to access class de.pottgames.tuningfork.SoundEffectData from class com.alfredo.games.FirstScreen (de.pottgames.tuningfork.SoundEffectData and com.alfredo.games.FirstScreen are in unnamed module of loader 'app')```
Maybe I just messed up something in Intellij because i followed the examples exactly like in the wiki.

**Comment by Hangman** [comment]
Hi, the code is right, I just checked just in case something broke in the last release but it didn't.
Maybe try `./gradlew build` or `./gradlew desktop:run` and see if that spits out the same error. Hope it's just a little gradle/IntelliJ hiccup.
If the error persists, feel free to post on the [libGDX Discord server](https://libgdx.com/community/discord/) or DM me directly if you want. I have the same name there.
